// Code generated by mockery v1.0.0. DO NOT EDIT.

package kail

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	time "time"

	v1alpha1 "github.com/projectriff/system/pkg/apis/streaming/v1alpha1"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// InMemoryGatewayLogs provides a mock function with given fields: ctx, gateway, since, out
func (_m *Logger) InMemoryGatewayLogs(ctx context.Context, gateway *v1alpha1.InMemoryGateway, since time.Duration, out io.Writer) error {
	ret := _m.Called(ctx, gateway, since, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.InMemoryGateway, time.Duration, io.Writer) error); ok {
		r0 = rf(ctx, gateway, since, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KafkaGatewayLogs provides a mock function with given fields: ctx, gateway, since, out
func (_m *Logger) KafkaGatewayLogs(ctx context.Context, gateway *v1alpha1.KafkaGateway, since time.Duration, out io.Writer) error {
	ret := _m.Called(ctx, gateway, since, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.KafkaGateway, time.Duration, io.Writer) error); ok {
		r0 = rf(ctx, gateway, since, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PulsarGatewayLogs provides a mock function with given fields: ctx, gateway, since, out
func (_m *Logger) PulsarGatewayLogs(ctx context.Context, gateway *v1alpha1.PulsarGateway, since time.Duration, out io.Writer) error {
	ret := _m.Called(ctx, gateway, since, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.PulsarGateway, time.Duration, io.Writer) error); ok {
		r0 = rf(ctx, gateway, since, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StreamingProcessorLogs provides a mock function with given fields: ctx, processor, since, out
func (_m *Logger) StreamingProcessorLogs(ctx context.Context, processor *v1alpha1.Processor, since time.Duration, out io.Writer) error {
	ret := _m.Called(ctx, processor, since, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Processor, time.Duration, io.Writer) error); ok {
		r0 = rf(ctx, processor, since, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
